### ISSUE TITLE
Does this repo handle packed multicodecs (byte prefix)?

### ISSUE THREAD

**Issue by Kubuxu** [multiformats/go-multicodec#27]
As multicodec-packed was deprecated, this should take over its role. I don't see where it defines packed multicodes or helper functions for decoding it.

**Comment by mvdan** [comment]
With permission from the rest of the IPLD team, I'm reviving this Go module to simply expose the multicodec table as code-generated Go constants. I'll be deleting all existing code in a commit (to preserve history) and will tag v0.2.0 once the new, simpler package is ready.

As such, I'm closing all previous issues. Thanks!
