### ISSUE TITLE
integrate flatbuffers

### ISSUE THREAD

**Issue by ghost** [multiformats/go-multicodec#29]
any interest is adding flatbuffers ?

https://google.github.io/flatbuffers/

https://github.com/google/flatbuffers

Its quite stable and is very similar to protobufs but higher performance.

**Comment by Stebalien** [comment]
I doubt anyone is against it however, protobufs "just work" for us for the moment so we're probably not going to invest any time into implementing this.

PRs welcome but we may take a while to review them.

**Comment by mvdan** [comment]
With permission from the rest of the IPLD team, I'm reviving this Go module to simply expose the multicodec table as code-generated Go constants. I'll be deleting all existing code in a commit (to preserve history) and will tag v0.2.0 once the new, simpler package is ready.

As such, I'm closing all previous issues. Thanks!
