### ISSUE TITLE
[question] what is the msgio param for?

### ISSUE THREAD

**Issue by florianlenz** [multiformats/go-multicodec#30]
Hi,

there is this struct: 
```go
type codec struct {
	mc    bool
	msgio bool
}
```
what is the `msgio` "flag" for? I couldn't find documentation for it.

**Comment by Stebalien** [comment]
If true, we length-prefix JSON objects with a varint length.

**Comment by Stebalien** [comment]
Warning: https://github.com/multiformats/go-multicodec/issues/24, https://github.com/multiformats/go-multicodec/pull/26
