### ISSUE TITLE
Support CRLF

### ISSUE THREAD

**Issue by skyline75489** [multiformats/go-multicodec#33]
It's been reported [here](https://github.com/ipfs/go-ipfs/issues/4490) that `go-multicodec` doesn't support CRLF as line ending.

**Comment by mvdan** [comment]
With permission from the rest of the IPLD team, I'm reviving this Go module to simply expose the multicodec table as code-generated Go constants. I'll be deleting all existing code in a commit (to preserve history) and will tag v0.2.0 once the new, simpler package is ready.

As such, I'm closing all previous issues. Thanks!
