### ISSUE TITLE
TODO: vendor everything with gx

### ISSUE THREAD

**Issue by jbenet** [multiformats/go-multicodec#4]
I'll vendor things using https://github.com/whyrusleeping/gx soon-- want to wait for the [license issue](https://github.com/whyrusleeping/cbor/issues/1) to resolve first.

**Comment by mvdan** [comment]
With permission from the rest of the IPLD team, I'm reviving this Go module to simply expose the multicodec table as code-generated Go constants. I'll be deleting all existing code in a commit (to preserve history) and will tag v0.2.0 once the new, simpler package is ready.

As such, I'm closing all previous issues. Thanks!
