### ISSUE TITLE
Automate code generation via CI

### ISSUE THREAD

**Issue by masih** [multiformats/go-multicodec#47]
Would it make sense to automate the code generated here by setting up a CI job that either runs periodically or watches the changes to the multicodec CSV file?

**Comment by mvdan** [comment]
I'd personally say "no", see https://github.com/multiformats/go-multicodec/pull/49#issuecomment-879746438

**Comment by lidel** [comment]
I think there is existential risk of not updating library to follow changes to `table.csv`
See the changes which were "missed" and i had to manually sync them: https://github.com/multiformats/go-multicodec/pull/71

## Desired state

See prior art in https://github.com/ipfs/ipfs-webui/pull/2049 – we have a CI that runs once a week  and if there are any changes, opens a PR + pings GUI team for review.

We want the same thing for this library:

1. Run once a week and see if `git submodule init && git submodule update --remote && go generate` produced any changes
2. IF there are changes, open a PR (if PR already exists, force-push latest version)

**Comment by lidel** [comment]
@galargh  would you or someone from IPDX be able to add this to your queue?

**Comment by galargh** [comment]
> @galargh would you or someone from IPDX be able to add this to your queue? 🙏

Sure, there you go - https://github.com/multiformats/go-multicodec/pull/72
