### ISSUE TITLE
walker interface 

### ISSUE THREAD

**Issue by jbenet** [multiformats/go-multicodec#7]
we may want a walker interface that walks objects as encoding/decoding happens, for very big things or small devices, where objects do not fit in memory easily.

**Comment by mvdan** [comment]
With permission from the rest of the IPLD team, I'm reviving this Go module to simply expose the multicodec table as code-generated Go constants. I'll be deleting all existing code in a commit (to preserve history) and will tag v0.2.0 once the new, simpler package is ready.

As such, I'm closing all previous issues. Thanks!
